version: "3.7"

services:
  tago-front:
    restart: always
    container_name: tago-front
    image: tago-front:1.0.0
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "29102:80"
    networks:
      - tago-network
      
networks: 
  tago-network:
    external: true